cols_to_target_encode:
  - City
  - Internet Service
  - Online Security
  - Online Backup
  - Device Protection
  - Tech Support
  - Streaming TV
  - Streaming Movies
  - Contract
  - Payment Method
  - Phone Service
  - Multiple Lines

cols_to_label_encode:
  - Senior Citizen
  - Partner
  - Dependents
  - Paperless Billing

cols_to_scale:
  - CLTV
  - Tenure Months
  - Monthly Charges
  - additional_services
  - 3rd_party_services

drop_cols:
  - Country
  - State
  - Zip Code
  - Latitude
  - Longitude
  - Churn Label
  - Churn Score
  - Churn Reason
  - Gender
  - Count
  - Lat Long
  - CustomerID

columns:
  - City
  - Senior Citizen
  - Partner
  - Dependents
  - Tenure Months
  - Phone Service
  - Multiple Lines
  - Internet Service
  - Online Security
  - Online Backup
  - Device Protection
  - Tech Support
  - Streaming TV
  - Streaming Movies
  - Contract
  - Paperless Billing
  - Payment Method
  - Monthly Charges
  - Total Charges
  - Churn Value
  - CLTV
  - additional_services
  - 3rd_party_services
  - is_payment_automatic
  - is_payment_recurring

numerical_columns:
  - Tenure Months
  - Monthly Charges
  - Total Charges
  - Churn Value
  - CLTV
  - additional_services
  - 3rd_party_services
  - is_payment_automatic
  - is_payment_recurring

target_column:
  - Churn Value